#!/bin/bash
# Can only be run in a safe deploy environment
if [ `\git status | \egrep -i 'nothing to commit, working tree clean' | \wc -l` = 0 ] ; then
  echo "ERROR: You cannot build for linux with checked out changes."
  exit 1
fi

for i in `find . -name '*.go' -print` ; do
  perl -i -ne 'print if (!/production:remove/i);' "$i"
done

GOOS=linux GOARCH=amd64 go build -o fiber-basic-auth
