#!/bin/bash -e -x
# Can only be run in a safe deploy environment
if [ `\git status | \egrep -i 'nothing to commit, working tree clean' | \wc -l` = 0 ] ; then
  echo "ERROR: You cannot deploy to production with checked out changes."
  exit 1
fi

./linux_build && \
  echo 'Insert your deploy command(s) here.'

# Go back to
git reset --hard HEAD
